site_name: My Docs

dev_addr: 0.0.0.0:8000

theme:
  # name: material
  name: readthedocs
  language: ja
  features:
    # ?
    - navigation.instant
    # Chapter is always open
    # - navigation.sections
    # all tree items are expanded
    - navigation.expand
    # ?
    - toc.integrate

plugins:
  # used for toctree macro in main.py
  - macros
  # work like [a normal link to that heading](../doc1.md#hello-world)
  - autorefs

#  - enumerate-headings:
#      increment_across_pages: true
#      # exclude:
#      #   - index.md
#   - markdown_inline_graphviz
#   - awesome-pages

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
        use_pygments: false
        noclasses: true
    - toc:
        permalink: true
    # - fontawesome_markdown
